#
# This action recreate action for building stable images
#
name: ABC
on:
  workflow_dispatch:
  repository_dispatch:
    types: [Recreate Matrix]

env:
  GH_TOKEN: ${{ secrets.REPO }}

jobs:


  build:
    name: Recreate action
    runs-on: ubuntu-latest
    steps:

    - name: Test
      run: |
        echo "ABC"
        gh api -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" /repos/igorpecovnik/scripts/actions/workflows
        sleep 20
        exit 1
        
  Stop:
    name: "Merge artifacts"
    if: failure()
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: "Runner clean"
        run: |
        
          WORKFLOW=$(gh api "/repos/armbian/os/actions/workflows" | jq '.workflows[] | select(.name=="Build Nightly Images (cronjob)")' | jq -r '.id')
          read ID STATUS ATTEMPT <<< $(gh api "/repos/armbian/os/actions/workflows/${WORKFLOW}/runs" | jq '.workflow_runs[]' | jq -r '.id,.conclusion,.run_attempt' | head -3 | xargs -n3 -d'\n')
          
          echo "ID=$ID STATUS=$STATUS ATTEMPT=$ATTEMPT"
          if [ "${ATTEMPT}" -lt 5 ]; then
          echo "Noch einmal"
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/igorpecovnik/scripts/actions/runs/${ID}/rerun-failed-jobs
          fi
          
