#
# This action recreate action for building stable images
#
name: Watchdog
on:
  workflow_dispatch:
  repository_dispatch:
    types: [Recreate Matrix]
jobs:
  table:
    runs-on: ubuntu-latest
    name: Update README from json data
    steps:
    - uses: actions/checkout@v2
    - name: Read/Write data into README
      uses: EddieHubCommunity/gh-actions-html-table-generator@v0.1.1
      with:
        json-file-path: 'merged.json'
        github-token: ${{ secrets.REPO }}
        columns: 7
        object-field-names: '[ "board_name", "u-boot", "kernel" , "iperf" , "sevenzip" , "armbian_monitor" , "kernel_target" ]'
        html-cell: '<tr><td align="left">{{ board_name }}</td><td align=left>{{ kernel_target }}</td><td align=right>{{ u-boot }}</td><td align=right>{{ kernel }}</td></tr><td align=right>{{ iperf }}</td><td aligh=right>{{ sevenzip }}</td><td align=right><a href="{{ armbian_monitor }}">Logs</a></td></tr>'
