#
# This action recreate action for building stable images
#
name: Watchdog
on:
  workflow_dispatch:
  repository_dispatch:
    types: [Recreate Matrix]
jobs:
  table:
    runs-on: ubuntu-latest
    name: Update README from json data
    steps:
    - uses: actions/checkout@v2
    - name: Read/Write data into README
      uses: eddiejaoude/github-actions-reader-writer@v0.1
      with:
        json-file-path: 'merged.json'
        github-token: ${{ secrets.REPO }}
        columns: 1
        object-field-names: '[ "board_name", "kernel_target", "u-boot", "kernel" , "iperf" , "sevenzip" , "armbian_monitor" ]'
        html-cell: '<td align="left">{{ board_name }}</td><td align=left>{{ kernel_target }}</td><td align=right>{{ u-boot }}</td><td align=right>{{ kernel }}</td><td align=right>{{ iperf }}</td><td align=right>{{ sevenzip }}</td><td align=right><a href="{{ armbian_monitor }}">Logs</a></td>'
