#
# This action recreate action for building stable images
#
name: Watchdog
on:
  workflow_dispatch:
  repository_dispatch:
    types: [Recreate Matrix]

env:
  GH_TOKEN: ${{ secrets.REPO }}

jobs:

  Check:
    name: "Merge artifacts"
    runs-on: ubuntu-latest
    steps:

      - name: "Read status"
        run: |
        
          WORKFLOW=$(gh api "/repos/armbian/os/actions/workflows" | jq '.workflows[] | select(.name=="Build Nightly Images (cronjob)")' | jq -r '.id')
          read ID STATUS ATTEMPT <<< $(gh api "/repos/armbian/os/actions/workflows/${WORKFLOW}/runs" | jq '.workflow_runs[]' | jq -r '.id,.conclusion,.run_attempt' | head -3 | xargs -n3 -d'\n')
          
          echo "ID=$ID STATUS=$STATUS ATTEMPT=$ATTEMPT"
          if [ "${ATTEMPT}" -lt 5 && "$STATUS" == "failure" ]; then
          echo "Noch einmal"
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/igorpecovnik/scripts/actions/runs/${ID}/rerun-failed-jobs
          fi
          
